WebMSFactory/Controllers/AllProductsController.cs
using MSFactoryDAC;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
namespace WebMSFactory.Controllers
{
    public class AllProductsController : Controller
    {
        ProductDAC dac = new ProductDAC();
        List<ProductList> NullList = new List<ProductList>();
        [HttpGet]
        public ActionResult Search(string Category = "전체", string ProductName = "", int page = 1)
        {
            int pageSize = 10000;
            
            DataTable dt = dac.SelectAllProducts(Category, page, pageSize);

            List<ProductList> list = SqlHelper.ConvertDataTableToList<ProductList>(dt);

            var SortedList = (from items in list
                              where items.Product_Name.Contains(ProductName)
                              select items).ToList();


            ProductListViewModel model = new ProductListViewModel
            {
                ComboList = dac.GetComboList(),
                Products = SortedList,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = dac.GetTotalCount(Category)
                },
                CurrentCategory = Category
            };

            return View(model);
        }

        public ActionResult DetailProduct(int ProductID)
        {
            ProductListViewModel model = new ProductListViewModel();

            model.ProductDetail = dac.DetailProduct(ProductID);

            List<ProductList> ForwardBom = dac.ProductBOM(true, ProductID);
            List<ProductList> ReverseBom = dac.ProductBOM(false, ProductID);

            if (ForwardBom != null)
                model.ForwardBom = ForwardBom;
            else
                model.ForwardBom = NullList;

            if (ReverseBom != null)
                model.ReverseBom = ReverseBom;
            else
                model.ReverseBom = NullList;

            return View(model);
        }
    }
}

WebMSFactory/Views/AllProducts/DetailProduct.cshtml
@model WebMSFactory.ProductListViewModel


@{
    ViewBag.Title = "<" + Model.ProductDetail.Product_Name + ">       상세 정보\n";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@ViewBag.Title</h1>
</div>

<div class="container-fluid">
    <div class="col-sm-12">
        <table class="table table-bordered dataTable">
            <colgroup>
                <col width="150">
                <col width="300">
                <col width="150">
                <col width="300">
                <col width="150">
                <col>
            </colgroup>
            <tbody>
                <tr>
                    <td class="font-weight-bold text-primary">제품 번호</td>
                    <td style="background-color: #fff;">@Model.ProductDetail.Product_ID</td>
                    <td class="font-weight-bold text-primary">제품 그룹명</td>
                    <td style="background-color: #fff;">@Model.ProductDetail.Product_Group_Name</td>
                    <td class="font-weight-bold text-primary">제품명</td>
                    <td style="background-color: #fff;">@Model.ProductDetail.Product_Name</td>
                </tr>
                <tr>
                    <td class="font-weight-bold text-primary">제품 스펙</td>
                    <td style="background-color: #fff;" colspan="3">@Model.ProductDetail.Product_Information</td>
                    <td class="font-weight-bold text-primary">기본 단위</td>
                    <td style="background-color: #fff;">@Model.ProductDetail.Product_Unit</td>
                </tr>
                <tr>
                    <td class="font-weight-bold text-primary">기준량</td>
                    <td style="background-color: #fff;">@Model.ProductDetail.Product_Standards</td>
                    <td class="font-weight-bold text-primary">Tact Time</td>
                    <td style="background-color: #fff;">@Model.ProductDetail.Product_Tact_Time</td>
                    <td class="font-weight-bold text-primary">Lead Time</td>
                    <td style="background-color: #fff;">@Model.ProductDetail.Product_Lead_Time</td>
                </tr>
                <tr>
                    <td class="font-weight-bold text-primary">비고1</td>
                    <td style="background-color: #fff;" colspan="5">@Model.ProductDetail.Product_Note1</td>
                </tr>
                <tr>
                    <td class="font-weight-bold text-primary">비고2</td>
                    <td style="background-color: #fff;" colspan="5">@Model.ProductDetail.Product_Note2</td>
                </tr>

            </tbody>
        </table>
    </div>
</div>

&nbsp;

@if (Model.ForwardBom.Count != 0)
{
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">정전개 목록</h1>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class=" text-primary">
                            <tr role="row">
                                <th class="sorting" rowspan="1" colspan="1" width="300px">제품명</th>
                                <th class="sorting" rowspan="1" colspan="1" width="400px">제품 스펙</th>
                                <th class="sorting" rowspan="1" colspan="1" width="100px">제품 수량</th>
                                <th class="sorting" rowspan="1" colspan="1" width="120px">제품 사용 여부</th>
                                <th class="sorting" rowspan="1" colspan="1" width="120px">제품 비고1</th>
                                <th class="sorting" rowspan="1" colspan="1" width="120px">제품 비고2</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var prod in Model.ForwardBom)
                            {
                                if (prod.LV == 0)
                                {
                                    <tr role="row">
                                        <td style="background-color:#EFEFFF">@prod.Product_Name</td>
                                        <td style="background-color:#EFEFFF">@prod.Product_Information</td>
                                        <td style="background-color:#EFEFFF">@prod.Bom_Use_Quantity</td>
                                        <td style="background-color:#EFEFFF">@prod.Product_Use</td>
                                        <td style="background-color:#EFEFFF">@prod.Product_Note1</td>
                                        <td style="background-color:#EFEFFF">@prod.Product_Note2</td>
                                    </tr>
                                }
                                else
                                {
                                    <tr role="row">
                                        <td>@prod.Product_Name</td>
                                        <td>@prod.Product_Information</td>
                                        <td>@prod.Bom_Use_Quantity</td>
                                        <td>@prod.Product_Use</td>
                                        <td>@prod.Product_Note1</td>
                                        <td>@prod.Product_Note2</td>
                                    </tr>
                                }

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

&nbsp;

@if (Model.ReverseBom.Count != 0)
{
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">역전개 목록</h1>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class=" text-primary">
                            <tr role="row">
                                <th class="sorting" rowspan="1" colspan="1" width="300px">제품명</th>
                                <th class="sorting" rowspan="1" colspan="1" width="400px">제품 스펙</th>
                                <th class="sorting" rowspan="1" colspan="1" width="100px">제품 수량</th>
                                <th class="sorting" rowspan="1" colspan="1" width="120px">제품 사용 여부</th>
                                <th class="sorting" rowspan="1" colspan="1" width="120px">제품 비고1</th>
                                <th class="sorting" rowspan="1" colspan="1" width="120px">제품 비고2</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var prod in Model.ReverseBom)
                            {
                                if (prod.LV == 0)
                                {
                                    <tr role="row">
                                        <td style="background-color:#EFEFFF">@prod.Product_Name</td>
                                        <td style="background-color:#EFEFFF">@prod.Product_Information</td>
                                        <td style="background-color:#EFEFFF">@prod.Bom_Use_Quantity</td>
                                        <td style="background-color:#EFEFFF">@prod.Product_Use</td>
                                        <td style="background-color:#EFEFFF">@prod.Product_Note1</td>
                                        <td style="background-color:#EFEFFF">@prod.Product_Note2</td>
                                    </tr>
                                }
                                else
                                {
                                    <tr role="row">
                                        <td>@prod.Product_Name</td>
                                        <td>@prod.Product_Information</td>
                                        <td>@prod.Bom_Use_Quantity</td>
                                        <td>@prod.Product_Use</td>
                                        <td>@prod.Product_Note1</td>
                                        <td>@prod.Product_Note2</td>
                                    </tr>
                                }

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

WebMSFactory/Views/AllProducts/Search.cshtml
@model WebMSFactory.ProductListViewModel
@{
    ViewBag.Title = "제품 관리";

}
@section title
{
    - @ViewBag.Title
}



<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@ViewBag.Title</h1>
</div>

<div class="col-md-12">
    <div class="card">
        <div class="card-header card-header-primary">

            <form style="padding-left:700px" action="~/AllProducts/Search">
                <select name="Category">
                    @foreach (var dicList in Model.ComboList)
                    {
                        <option value="@dicList">@dicList</option>
                    }
                </select>
                <input type="text" name="ProductName" />
                <input type='submit' value='검색'>
            </form>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class=" text-primary">
                        <tr role="row">
                            <th class="sorting" rowspan="1" colspan="1" col-3 width="100px">순번</th>
                            <th class="sorting" rowspan="1" colspan="1" width="350px">그룹 이름</th>
                            <th class="sorting" rowspan="1" colspan="1" width="400px">제품 이름</th>
                            <th class="sorting" rowspan="1" colspan="1" width="100px">제품 사용 여부</th>
                            <th class="sorting" rowspan="1" colspan="1" width="200px">제품 상세 보기 / BOM</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var prod in Model.Products)
                        {
                            <tr role="row">
                                <td>@prod.Num</td>
                                <td>@prod.Product_Group_Name</td>
                                <td>@prod.Product_Name</td>
                                <td>@prod.Product_Use</td>
                                <td>
                                    @Html.ActionLink("상세보기", "DetailProduct", "AllProducts",
                                    new
                                    {
                                        ProductID = prod.Product_ID
                                    }, new { @class = "btn btn-primary btn-sm" }
                                    )
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>